### ISSUE TITLE
Improve results page

### ISSUE THREAD

**Issue by cloudhary** [cloudhary/okayornot#10]
We need to show more data to prompt reflection. This PR is not yet very well defined, so some more discussion is necessary before coding it up. A few suggestions I've heard:

1. showing the three statements that they have been shown to agree the most with
2. showing which demographic groups they have most in common with and least in common with (watch out ah, this can be risky!)
3. ~show the percentage "okay or not" for ALL statements~ see #27 
4. show percentage for each statement based on demographic breakdown

In my opinion, we should do point 1 and 2 and 3 before this new launch, number 4 and other prettier displays can come later

**Comment by mantariksh** [comment]
I think point number 2 warrants further discussion in terms of design and implementation. For now I've re-styled 1 and implemented 4.

**Comment by cloudhary** [comment]
The results page is good enough now, let's close this issue unless someone else comments with improvements/suggestions
