### ISSUE TITLE
Set up Netlify Badges and request open source freebies from them

### ISSUE THREAD

**Issue by cloudhary** [cloudhary/okayornot#28]
Currently, we're on a limited Netlify plan that doesn't let me add others to it. If we're keen on getting more folks to see the project, we can get sponsored by Netlify. I reached out and Scott Parker at Netlify responded with:

You can read more about what we provide to qualified open source projects for free here:
https://www.netlify.com/legal/open-source-policy/ .

Please note that while this is a free account, it is not an unlimited account - please carefully review the limitations for the paid Pro plan here: https://www.netlify.com/pricing/#teams - your project will still be financially liable for overages in bandwidth, build minutes, form submissions, and the like above the Pro plan limits (except for contributors, which are unlimited on the sponsored plan).

Take a look and let me know when your project is compatible with that definition, specifically that it meets all of the below criteria:

1. uses a public git repository,
2. features a prominently visible code of conduct for participation in your project,
3. and has an open source license, such as the ones listed here: https://opensource.org/licenses or a creative commons license for the content.
4. finally, these accounts are not intended for use on commercial projects. This prohibition includes commercial support and hosting services.

Further, we require a link to our service on your project's main web page for your website's visitors to see (so, not just in your repository documentation or on a sponsors page). You have two options: we have premade badges for your convenience, or you may create your own link, which should read “This site is powered by Netlify”.
Either should link back to our home page, https://www.netlify.com.

Once these are true and confirmed, we'd be happy to sponsor this project!

**Comment by gauravkeerthi** [comment]
Happy to pay if required. What's the next tier up from free?
