### ISSUE TITLE
integrating a 3rd party discussion platform or social media commenting system

### ISSUE THREAD

**Issue by gauravkeerthi** [cloudhary/okayornot#29]
Our platform now has no user engagement beyond the experience of playing the game. Ideally, we could integrate a commenting system (eg disqus, facebook) instead of building the code on our own. This can be on the last page (after submitting), as a form of reflection from the user. 
As an alternative to embedding comments (which can be a UI headache), we could enable them to "share" it on social media and encourage them to write about their experience so that they can have conversations with their social network online. Less ideal (because users would not see any evidence that others are discussing this when they visit, unless we can show that somehow) but both options work for me.

**Comment by cloudhary** [comment]
> As an alternative to embedding comments (which can be a UI headache), we could enable them to "share" it on social media and encourage them to write about their experience so that they can have conversations with their social network online. Less ideal (because users would not see any evidence that others are discussing this when they visit, unless we can show that somehow) but both options work for me.

I like this idea. Let's brainstorm how we should encourage sharing. What exactly is worth sharing about? Let me bring this over to the whatsapp group

**Comment by cloudhary** [comment]
Will be temporarily addressed by #6
