### ISSUE TITLE
Set the context before you start the quiz with instructions/prompts

### ISSUE THREAD

**Issue by cloudhary** [cloudhary/okayornot#62]

**Comment by mantariksh** [comment]
My plan:
1. On the landing page, change "See how your responses compare to others." to "At the end, we'll show you how similar or different your answers were from others who have responded."
2. On the questions page, add an initial card which says the following:
    - Desktop: "Indicate whether you think these statements are okay or not by clicking the buttons below, using your arrow keys or dragging the cards. Left means "not okay", right means "okay". Select "okay" for this card to get started!"
    - Mobile: "Indicate whether you think these statements are okay or not by swiping the cards or clicking the buttons below. Left means "not okay", right means "okay". Select "okay" for this card to get started!"

**Comment by cloudhary** [comment]
I like your thoughts. What if folks actually select not okay?

**Comment by mantariksh** [comment]
Err I was thinking of just doing nothing. Or we could allow them to select either okay or not okay to proceed. Or we could block their IP and try to insert malware into their browser. Whatever saahib wishes

**Comment by cloudhary** [comment]
> Whatever saahib wishes

HAHAHAHHHAH I diedddddd

**Comment by cloudhary** [comment]
Took me a minute to calm down, damn. Alright. Let's go with the "do nothing" option!
