### ISSUE TITLE
About page parity with Figma mocks

### ISSUE THREAD

**Issue by cloudhary** [cloudhary/okayornot#64]
https://www.figma.com/file/z2w9fr7VKgheTAPcZK4V4Y/Okay%2FNot?node-id=0%3A1

**Comment by eric-tong** [comment]
How much parity are we going for? There's a fair bit of difference between existing and mock pages.

**Comment by cloudhary** [comment]
Right, I agree @eric-tong. I was hoping to actually do the new "cardless" interface, with swiping on the left and right. @mantariksh @Waffleboy @arshadali172 thoughts?

**Comment by mantariksh** [comment]
How does the "cardless" interface work? I see the design but I don't understand the UX. I was actually just gonna say to prioritise the About and Results pages instead haha.

**Comment by cloudhary** [comment]
@mantariksh we might need to hop on the phone with Pearly to understand what she has in mind. I agree. Let's clean up the about page in the interim.

**Comment by cloudhary** [comment]
I agree with @arshadali172, we need to define this PR much more. I'm going to narrow the scope of this PR. Let's get parity on the About page with the mocks

![image](https://user-images.githubusercontent.com/10901999/87848941-5a9eaa80-c917-11ea-92af-f0891f688562.png)

**Comment by mantariksh** [comment]
Assigning @eric-tong to work on this after the feedback section
