### ISSUE TITLE
Desktop experience

### ISSUE THREAD

**Issue by cloudhary** [cloudhary/okayornot#7]
We currently do not support desktop. There are some mocks available for the desktop experience, but this is a lot of work, so we need to ask the question of how important it is to actually do so. Currently tagged as P2

**Comment by cloudhary** [comment]
@mantariksh is working on this too? I'm not sure. More clarity required.

**Comment by gauravkeerthi** [comment]
https://codepen.io/bmarcelino/pen/pLzYjE

This is a simple way to adapt the code to a desktop experience. Just add buttons at the bottom that call the same function as the swipe!

**Comment by mantariksh** [comment]
> @mantariksh is working on this too?

should be fine, I'm aiming to finish up aggregate stats by tomorrow so I can pick this up after

**Comment by mantariksh** [comment]
@arshadali172 
- [ ] Almost done
- [ ] Results
- Share your story

@mantariksh 
- [ ] Quiz
- [ ] Aggregate results

**Comment by cloudhary** [comment]
> https://codepen.io/bmarcelino/pen/pLzYjE

That's what I used!

**Comment by mantariksh** [comment]
I realised that if we're going to have both desktop and mobile experiences, the redirect from /index to /landing_page won't be necessary. Here's my proposal for the new flow for both desktop and mobile:

1. Change `/home` to `/index` and `/index` to `/questions`. This means that visiting okayornot.sg on both mobile and desktop leads to the intro page, and you have to click "Start" to see the questions. Then we can get rid of `landing_page`.
2. If your URL contains a valid room ID, then you will also see a "Results for this room" button under the "Start" button. This leads to the aggregate results page.

@cloudhary @arshadali172 thoughts?

**Comment by arshadali172** [comment]
> I realised that if we're going to have both desktop and mobile experiences, the redirect from /index to /landing_page won't be necessary. Here's my proposal for the new flow for both desktop and mobile:
> 
> 1. Change `/home` to `/index` and `/index` to `/questions`. This means that visiting okayornot.sg on both mobile and desktop leads to the intro page, and you have to click "Start" to see the questions. Then we can get rid of `landing_page`.
> 2. If your URL contains a valid room ID, then you will also see a "Results for this room" button under the "Start" button. This leads to the aggregate results page.
> 
> @cloudhary @arshadali172 thoughts?

great idea, love it! `okayornot.sg` should just default to the home page, as you explained.

to clarify, the aggregate results page just shows all the results, without comparing it to your results?

and the only way to see your results compared to the global results is to play the game and land on the results page?

**Comment by mantariksh** [comment]
> to clarify, the aggregate results page just shows all the results, without comparing it to your results?

Yup

> and the only way to see your results compared to the global results is to play the game and land on the results page?

Yeah but actually on second thoughts from a product POV, I don't think we should allow users to view the global results without participating in the game.

I previously suggested linking to the "Aggregated Results" page from the "Your Results" page, but we decided against it because the former was a purely desktop view while the latter was purely mobile. Now that everything is going to be available on desktop, I think that idea is the best approach to encourage people to participate.

**Comment by cloudhary** [comment]
> I previously suggested linking to the "Aggregated Results" page from the "Your Results" page, but we decided against it because the former was a purely desktop view while the latter was purely mobile. Now that everything is going to be available on desktop, I think that idea is the best approach to encourage people to participate.

what about let's just make it a hidden page that only facilitators who know about it can get to it?

**Comment by mantariksh** [comment]
> what about let's just make it a hidden page that only facilitators who know about it can get to it?

But do we want default room users to never be able to see the aggregate results? If that's the case, we should have a more in-depth discussion on #10 about what demographic information we want to show to individual users.

**Comment by gauravkeerthi** [comment]
why not show the aggregate results to all users at the end of the quiz (instead of at the beginning?)
i don't know if all quizzes will have a facilitator, and not seeing results after filling in the quiz is quite... a let down

**Comment by mantariksh** [comment]
Righto here's my plan:
- The existing content on the results page (your % of okay vs the majority, your questions with greatest difference from majority) will stay the same except the percentage bars will be restyled to plain black bars like in the aggregate results page.
- Below the existing content, I'll add in a personalised version of the aggregate results, which will look exactly the same as the aggregate results except each question will also contain the user's answer, e.g. "You answered: okay!".

I'm starting work on this now, ping me if you have any suggestions!
